language: shell

matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux 
      dist: trusty

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - wget https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh
  - sudo chmod +x ols1clk.sh
  - echo 'Y' | sudo bash ols1clk.sh --lsphp 74 --wordpress