language: shell

matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux 
      dist: trusty
    - os: linux
      dist: precise     

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - sudo su -c "bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh ) --lsphp 73"
