language: shell

matrix:
  include:
    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
    - os: linux 
      dist: trusty
    - os: linux
      dist: precise     

notifications:
  email:
    on_success: never
    on_failure: always

script:
  - sudo apt-get remove --purge mysql* -y
  - sudo su -c "bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Setup/wpimgsetup.sh )"
  - sudo su -c "bash <( curl -sk https://raw.githubusercontent.com/litespeedtech/ls-cloud-image/master/Cloud-init/per-instance.sh )"
  - curl -s http://127.0.0.1/ | grep 'OpenLiteSpeed WordPress One-Click'