  
name: ols1clk

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lsws1clk test
        run: |
          sudo apt remove --purge mysql*; 
          sudo systemctl daemon-reload
          sudo bash ols1clk.sh -W --pure-mariadb