  
name: ols1clk

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: ols1clk installation 
        run: |
          sudo apt-get remove --purge mysql* -y
          sudo apt-get autoremove -y
          sudo apt-get autoclean -y
          sudo rm -rf /etc/mysql /var/lib/mysql /var/log/mysql
          sudo bash ols1clk.sh -W --quiet 
      - name: ols1clk verify     
          run: curl -skL  http://localhost/ | grep -i "WordPress" >/dev/null 2>&1
      - name: ols1clk uninstallation    
        run: sudo bash ols1clk.sh -U --quiet 